### ISSUE TITLE
Getting too many shells

### ISSUE THREAD

**Issue by 20e8jmve** [Knowledge-Wisdom-Understanding/recon#6]
This tool is too guud.  Make a website with fancy pictures, sell this, and buy big boat.

**Comment by Knowledge-Wisdom-Understanding** [comment]
Thanks! @20e8jmve Glad you like my project! I wouldn't feel comfortable selling this as it uses many other people's tools (nmap, dirsearch, aquatone, etc..) in conjunction with some of my own relatively simple modules. A website would be nice. Perhaps I'll throw one together some day soon. I appreciate the kind words. Much obliged. 💯
